import os

SUPABASE_URL = os.getenv("COZE_SUPABASE_URL", "")
SUPABASE_SERVICE_KEY = os.getenv("SUPABASE_SERVICE_ROLE_KEY") or os.getenv("COZE_SUPABASE_SERVICE_ROLE_KEY", "")
SUPABASE_ANON_KEY = os.getenv("COZE_SUPABASE_ANON_KEY", "")
REST_URL = f"{SUPABASE_URL}/rest/v1"
FASTAPI_PORT = 8000
